import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContext, AuthProvider } from "./contexts/AuthContext";
import Navigation from "./components/Navigation";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aonde IR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AuthProvider>
          <main className="flex-grow">{children}</main>
          <Navigation />
        </AuthProvider>
      </body>
    </html>
  );
}
